# Generated by Django 4.1.4 on 2022-12-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
