# Generated by Django 4.1.4 on 2022-12-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_article_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(),
        ),
    ]
